# Generated by Django 2.1.15 on 2020-05-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_standarkompetensi_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standarkompetensi',
            old_name='short',
            new_name='tipe',
        ),
    ]
