# Generated by Django 2.1.15 on 2021-05-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_paketsoal_kurikulum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketsoal',
            name='kurikulum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
