# Generated by Django 2.1.15 on 2020-05-17 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20200516_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_soal', models.TextField()),
                ('generated_option', models.TextField(null=True)),
                ('generated_correct_option', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indikator_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Indikator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaketSoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('judul', models.CharField(max_length=20)),
                ('jumlah_paket', models.IntegerField()),
                ('id_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Soal_PaketSoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_soal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.GeneratedSoal')),
                ('paket_soal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.PaketSoal')),
            ],
        ),
        migrations.CreateModel(
            name='StatusSoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='soal',
            name='created_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='soal',
            name='indikator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Indikator'),
        ),
        migrations.AddField(
            model_name='generatedsoal',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Soal'),
        ),
        migrations.AddField(
            model_name='soal',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.StatusSoal'),
        ),
    ]
