# Generated by Django 2.1.15 on 2021-05-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210526_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soal',
            old_name='indikator',
            new_name='penugasan',
        ),
    ]
