# Generated by Django 2.1.15 on 2020-05-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20200517_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisiSoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField()),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Soal')),
            ],
        ),
    ]
