# Generated by Django 2.1.15 on 2021-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210527_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penugasan',
            name='kurikulum',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
