# Generated by Django 2.1.15 on 2021-06-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_revisisoal_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='rebuild',
            field=models.TextField(null=True),
        ),
    ]
