# Generated by Django 2.1.15 on 2021-06-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_soal_rebuild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soal',
            name='rebuild',
        ),
    ]
