# Generated by Django 2.1.15 on 2020-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200518_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='var1',
            field=models.CharField(max_length=100),
        ),
    ]
