# Generated by Django 2.1.15 on 2020-05-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200518_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='paketsoal',
            name='kurikulum',
            field=models.IntegerField(null=True),
        ),
    ]
