# Generated by Django 2.1.15 on 2020-05-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_paketsoal_kurikulum'),
    ]

    operations = [
        migrations.AddField(
            model_name='paketsoal',
            name='generated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paketsoal',
            name='is_generated',
            field=models.BooleanField(null=True),
        ),
    ]
