# Generated by Django 2.1.15 on 2020-05-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20200527_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedsoal',
            name='generated_correct_option',
        ),
        migrations.AddField(
            model_name='soal_paketsoal',
            name='nomer_paket',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='soal_paketsoal',
            name='nomer_urut',
            field=models.IntegerField(null=True),
        ),
    ]
