# Generated by Django 2.1.15 on 2020-05-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20200527_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='variabel_gambar',
            field=models.TextField(default='---'),
            preserve_default=False,
        ),
    ]
