# Generated by Django 2.1.15 on 2020-05-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_soal_variabel_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal_paketsoal',
            name='paket_soal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.PaketSoal'),
        ),
    ]
