# Generated by Django 2.1.15 on 2021-05-31 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20200602_2054'),
        ('quiz', '0008_revisisoal_id_user'),
    ]

    operations = [
    ]
