# Generated by Django 2.1.15 on 2021-05-31 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_merge_20210531_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indikator_user',
            name='penugasan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Penugasan'),
        ),
        migrations.AlterField(
            model_name='soal',
            name='indikator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Penugasan'),
        ),
        migrations.AlterField(
            model_name='soal',
            name='variabel_gambar',
            field=models.TextField(null=True),
        ),
    ]
