# Generated by Django 2.1.15 on 2021-06-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_soal_rebuild'),
        ('quiz', '0020_auto_20210531_1038'),
    ]

    operations = [
    ]
