# Generated by Django 2.1.15 on 2021-06-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_auto_20210620_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indikator',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='indikator',
            name='kompetensi_dasar',
        ),
        migrations.RemoveField(
            model_name='kompetensidasar',
            name='StandarKompetensi',
        ),
        migrations.RemoveField(
            model_name='kompetensidasar',
            name='materi',
        ),
        migrations.DeleteModel(
            name='Indikator',
        ),
        migrations.DeleteModel(
            name='KompetensiDasar',
        ),
        migrations.DeleteModel(
            name='Materi',
        ),
        migrations.DeleteModel(
            name='StandarKompetensi',
        ),
    ]
