# Generated by Django 4.0.4 on 2022-05-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20210620_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subskripsi_email',
            field=models.BooleanField(default=True),
        ),
    ]
