# Generated by Django 4.0.4 on 2022-05-26 09:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20210620_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='jawaban',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='soal',
            name='soal',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='templatesoal',
            name='jawaban',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='templatesoal',
            name='soal',
            field=models.TextField(null=True),
        ),
    ]
