# Generated by Django 4.0.4 on 2022-05-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_alter_soal_jawaban_alter_soal_soal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='jawaban',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='templatesoal',
            name='jawaban',
            field=models.TextField(null=True),
        ),
    ]
