# Generated by Django 4.0.4 on 2022-05-26 10:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_alter_soal_jawaban_alter_templatesoal_jawaban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='jawaban',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='soal',
            name='soal',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='templatesoal',
            name='jawaban',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='templatesoal',
            name='soal',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
