# Generated by Django 4.0.4 on 2022-06-15 03:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_alter_soal_jawaban_alter_soal_soal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='soal',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
