# Generated by Django 4.0.4 on 2022-06-15 03:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_alter_soal_soal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='soal',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
