# Generated by Django 4.0.4 on 2022-06-23 04:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_alter_soal_soal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='jawaban',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='templatesoal',
            name='jawaban',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='templatesoal',
            name='soal',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
