# Generated by Django 4.0.4 on 2022-06-29 02:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_alter_soal_jawaban_alter_templatesoal_jawaban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='variabel',
            field=tinymce.models.HTMLField(),
        ),
    ]
