# Generated by Django 4.0.4 on 2022-06-29 02:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_alter_soal_variabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatesoal',
            name='variabel',
            field=tinymce.models.HTMLField(),
        ),
    ]
