# Generated by Django 4.0.4 on 2022-07-03 00:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_alter_templatesoal_var1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatesoal',
            name='var1',
            field=tinymce.models.HTMLField(),
        ),
    ]
