# Generated by Django 3.2.14 on 2022-08-01 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0034_alter_templatesoal_var1'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subskripsi_email',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Peninjau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_penunjukkan', models.DateTimeField()),
                ('peninjau_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peninjau', to=settings.AUTH_USER_MODEL)),
                ('penunjuk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penunjuk', to=settings.AUTH_USER_MODEL)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.soal')),
            ],
        ),
    ]
