# Generated by Django 3.2.15 on 2022-08-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_peninjau'),
        ('quiz', '0035_auto_20220801_2251'),
    ]

    operations = [
    ]
