# Generated by Django 4.0.4 on 2022-09-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_templatesoal2'),
    ]

    operations = [
        migrations.AddField(
            model_name='indikator_user',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.templatesoal2'),
        ),
    ]
