# Generated by Django 4.0.4 on 2022-09-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_indikator_user_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indikator_user',
            name='template',
        ),
    ]
