# Generated by Django 3.2.15 on 2022-08-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0037_auto_20220822_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPaketSoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
