# Generated by Django 3.2.15 on 2022-08-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_statuspaketsoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='paketsoal',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.statuspaketsoal'),
        ),
    ]
