# Generated by Django 3.2.15 on 2022-08-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0040_auto_20220823_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilreview',
            name='kejelasan_bahasa',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hasilreview',
            name='kejelasan_gambar',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hasilreview',
            name='kesesuaian_cpmk',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hasilreview',
            name='kesesuaian_waktu',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hasilreview',
            name='komentar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hasilreview',
            name='peninjau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.peninjau'),
        ),
        migrations.AddField(
            model_name='hasilreview',
            name='soal_paketSoal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.soal_paketsoal'),
        ),
    ]
