# Generated by Django 3.2.15 on 2022-08-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_auto_20220824_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilreview',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
