# Generated by Django 3.2.15 on 2022-08-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0043_hasilreview_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='peninjau',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.statuspaketsoal'),
        ),
    ]
