# Generated by Django 3.2.15 on 2022-09-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0041_templatesoal_id_user_delete_templatesoal2'),
        ('quiz', '0044_peninjau_status'),
    ]

    operations = [
    ]
