# Generated by Django 3.2.15 on 2022-09-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0045_merge_20220908_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilreview',
            name='kejelasan_bahasa',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='hasilreview',
            name='kejelasan_gambar',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='hasilreview',
            name='kesesuaian_cpmk',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='hasilreview',
            name='kesesuaian_waktu',
            field=models.IntegerField(default=3),
        ),
    ]
